# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kPNmHWUKT4fBzx9QiC4v8m9rKGXUsu2L
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import shap
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

# File load karein (ensure karein file ka naam wahi ho jo aapne upload ki hai)
df = pd.read_csv('StudentsPerformance.csv')

# Check karein data kaisa dikh raha hai
print(df.head())

# Sirf text wale columns ko select karke unhe encode karein
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = le.fit_transform(df[col])

print("Data successfully encoded!")
print(df.head()) # Ab aapko sirf numbers dikhenge

# X = Inputs, y = Output (Math Score)
X = df.drop('math score', axis=1)
y = df['math score']

# 80% data training ke liye aur 20% testing ke liye
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training data size: {X_train.shape}")
print(f"Testing data size: {X_test.shape}")

# Model initialize aur train karein
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

print("Model Training Complete!")


# Predictions nikalna
y_pred = model.predict(X_test)

# Accuracy scores calculate karna
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Absolute Error: {mae:.2f} marks")
print(f"R-squared Score (Accuracy): {r2*100:.2f}%")


plt.figure(figsize=(8,5))
sns.regplot(x=y_test, y=y_pred, ci=None, color="blue")
plt.xlabel("Actual Marks")
plt.ylabel("Predicted Marks")
plt.title("Student Performance Prediction Accuracy")
plt.show()


# Model training ke baad ye cell add karein
importances = model.feature_importances_
features = X.columns
feature_importance_df = pd.DataFrame({'Feature': features, 'Importance': importances}).sort_values(by='Importance', ascending=False)

plt.figure(figsize=(10,6))
sns.barplot(x='Importance', y='Feature', hue='Feature', data=feature_importance_df, palette='viridis', legend=False)
plt.title('Feature Importance: Factors Affecting Math Scores')
plt.show()


# Risk Alert Function
def check_student_risk(student_index):
    # Test set se ek student uthayiye
    student_data = X_test.iloc[[student_index]]
    actual_marks = y_test.iloc[student_index]
    predicted_marks = model.predict(student_data)[0]

    print(f"Actual Marks: {actual_marks}")
    print(f"Predicted Marks: {predicted_marks:.2f}")

    if predicted_marks < 40:
        print("🚨 STATUS: CRITICAL - High Risk of Failure!")
    elif predicted_marks < 60:
        print("⚠️ STATUS: WARNING - Below Average Performance.")
    else:
        print("✅ STATUS: SAFE - Student is on track.")

# Kisi bhi student ka index daal kar check karein (e.g., 5th student)
check_student_risk(5)



# Explainer create karein
explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X_test)

# Pehle student ke liye explanation plot karein
shap.initjs()
shap.force_plot(explainer.expected_value, shap_values[0,:], X.iloc[0,:])